use_frameworks!

platform :ios, '10.0'

target 'ZLStreamingTextView_Example' do
  pod 'ZLStreamingTextView', :path => '../'

  target 'ZLStreamingTextView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
